/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasakhirfathin;


/**
 *
 * @author user
 */
public class userlogin extends javax.swing.JFrame {
    private String[][] Pesanan = new String[16][2];
    /**
     * Creates new form 
     */
    public userlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        nBlackCoffee2 = new javax.swing.JTextField();
        nBlackCoffee5 = new javax.swing.JTextField();
        nBlackCoffee13 = new javax.swing.JTextField();
        nBlackCoffee14 = new javax.swing.JTextField();
        nBlackCoffee16 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nAmeric = new javax.swing.JCheckBox();
        nDoppioo = new javax.swing.JCheckBox();
        nMachiaato = new javax.swing.JCheckBox();
        nExpresso = new javax.swing.JLabel();
        nBlackCoffee = new javax.swing.JTextField();
        nDoppio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nOriginThaitea = new javax.swing.JCheckBox();
        nThaiteaGreenTea = new javax.swing.JCheckBox();
        nThaiOvaltine = new javax.swing.JCheckBox();
        nThaiTaro = new javax.swing.JCheckBox();
        nGreentea = new javax.swing.JTextField();
        nOrigin = new javax.swing.JTextField();
        nOvaltine = new javax.swing.JTextField();
        nMachiato = new javax.swing.JTextField();
        nIceTaro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nCoffeeLattee = new javax.swing.JCheckBox();
        nAvocadLatte = new javax.swing.JCheckBox();
        nAmericano1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nVanillashake = new javax.swing.JCheckBox();
        nChocolateshake = new javax.swing.JCheckBox();
        nStrawberryshake = new javax.swing.JCheckBox();
        nCaramelLatte = new javax.swing.JCheckBox();
        nMatchaLatte = new javax.swing.JCheckBox();
        nVanilla = new javax.swing.JTextField();
        nChocolate = new javax.swing.JTextField();
        nMatcha = new javax.swing.JTextField();
        nCofeeLatte = new javax.swing.JTextField();
        nAvocad = new javax.swing.JTextField();
        nCaramel = new javax.swing.JTextField();
        nStrawberry = new javax.swing.JTextField();
        nCooekiesCream = new javax.swing.JCheckBox();
        nCookies = new javax.swing.JTextField();
        pemesanan = new javax.swing.JButton();
        nBlackC = new javax.swing.JCheckBox();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELAMAT DATANG DI KALA SENJA");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        nAmeric.setText("Americano");

        nDoppioo.setText("Doppio");

        nMachiaato.setText("Macchiato");

        nExpresso.setText("Expresso");

        nBlackCoffee.setBackground(new java.awt.Color(255, 204, 204));

        nDoppio.setBackground(new java.awt.Color(255, 204, 204));

        jLabel3.setText("Thai Tea");

        nOriginThaitea.setText("Original Thai Tea");

        nThaiteaGreenTea.setText("Thai Ice Green Tea");

        nThaiOvaltine.setText("Thai Ice Ovaltine");

        nThaiTaro.setText("Thai Ice Taro");

        nGreentea.setBackground(new java.awt.Color(255, 204, 204));

        nOrigin.setBackground(new java.awt.Color(255, 204, 204));

        nOvaltine.setBackground(new java.awt.Color(255, 204, 204));

        nMachiato.setBackground(new java.awt.Color(255, 204, 204));

        nIceTaro.setBackground(new java.awt.Color(255, 204, 204));

        jLabel5.setText("Latte");

        nCoffeeLattee.setText("Coffee Latte");

        nAvocadLatte.setText("Avocado Latte");

        nAmericano1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel6.setText("Shake");

        nVanillashake.setText("Vanilla Shake");

        nChocolateshake.setText("Chocolate Shake");

        nStrawberryshake.setText("Strawberry shake");

        nCaramelLatte.setText("Caramel Latte");

        nMatchaLatte.setText("Matcha Latte");

        nVanilla.setBackground(new java.awt.Color(255, 204, 204));
        nVanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nVanillaActionPerformed(evt);
            }
        });

        nChocolate.setBackground(new java.awt.Color(255, 204, 204));

        nMatcha.setBackground(new java.awt.Color(255, 204, 204));

        nCofeeLatte.setBackground(new java.awt.Color(255, 204, 204));

        nAvocad.setBackground(new java.awt.Color(255, 204, 204));

        nCaramel.setBackground(new java.awt.Color(255, 204, 204));

        nStrawberry.setBackground(new java.awt.Color(255, 204, 204));

        nCooekiesCream.setText("Cookies and Cream");

        nCookies.setBackground(new java.awt.Color(255, 204, 204));

        pemesanan.setText("order");
        pemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemesananActionPerformed(evt);
            }
        });

        nBlackC.setText("Black Coffee");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nExpresso, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(nThaiteaGreenTea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nThaiOvaltine, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(nOriginThaitea, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nThaiTaro, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nDoppio)
                                        .addComponent(nBlackCoffee)
                                        .addComponent(nAmericano1, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                                        .addComponent(nGreentea)
                                        .addComponent(nOrigin)
                                        .addComponent(nMachiato)
                                        .addComponent(nOvaltine))
                                    .addComponent(nIceTaro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nAmeric, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(nMachiaato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nDoppioo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nBlackC, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(nCooekiesCream, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                        .addComponent(nStrawberryshake, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nStrawberry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nCookies, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nChocolateshake, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nVanillashake))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nVanilla, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                                        .addComponent(nChocolate, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                                        .addComponent(nMatcha, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                                        .addComponent(nCaramel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                                        .addComponent(nAvocad, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                                        .addComponent(nCofeeLatte))))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nCoffeeLattee, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nAvocadLatte, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nCaramelLatte, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nMatchaLatte, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nExpresso)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nBlackCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nCoffeeLattee)
                            .addComponent(nCofeeLatte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nBlackC)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nAvocad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nAmeric)
                        .addComponent(nAvocadLatte)
                        .addComponent(nAmericano1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nDoppioo)
                    .addComponent(nDoppio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nCaramelLatte)
                    .addComponent(nCaramel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nMachiaato)
                    .addComponent(nMachiato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nMatchaLatte)
                    .addComponent(nMatcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nThaiteaGreenTea)
                                    .addComponent(nGreentea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nOriginThaitea)
                                .addComponent(nOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nThaiOvaltine)
                            .addComponent(nOvaltine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nThaiTaro)
                            .addComponent(nIceTaro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nVanillashake)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nVanilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nChocolateshake))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nStrawberryshake)
                            .addComponent(nStrawberry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nCooekiesCream)
                            .addComponent(nCookies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(pemesanan)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemesananActionPerformed
        if (nBlackC.isSelected()==true){
            Pesanan[0][0] = "Black Cofee";
            Pesanan[0][1] = nBlackCoffee.getText();
        }
        if(nAmeric.isSelected()==true){
            Pesanan[1][0] = "Americano";
            Pesanan[1][1] = nAmericano1.getText();
        }
        if(nDoppioo.isSelected()==true) {
            Pesanan [2][0] = "Doppio";
            Pesanan [2][1] = nDoppio.getText();
        }
        if (nMachiaato.isSelected()==true) {
            Pesanan [3][0] = "Macchiato";
            Pesanan [3][1] = nMachiato.getText();
        }
        if (nOriginThaitea.isSelected()==true) {
            Pesanan [4][0] = "Original Thai Tea";
            Pesanan [4][1] = nOrigin.getText();
        }
        if (nThaiteaGreenTea.isSelected()==true) {
            Pesanan [5][0] = "Thai Tea Green Tea";
            Pesanan [5][1] = nGreentea.getText();
        }
        if (nThaiOvaltine.isSelected()==true) {
            Pesanan [6][0] = "Thai Ice Ovaltine";
            Pesanan [6][1] = nOvaltine.getText();
        }
        if (nThaiTaro.isSelected()==true){
            Pesanan [7][0] = "Thai Ice Taro";
            Pesanan [7][1] = nIceTaro.getText();
        }
        if (nCoffeeLattee.isSelected()==true){
            Pesanan [8][0] = "Coffee Latte";
            Pesanan [8][1] = nCofeeLatte.getText();
        }
        if (nAvocadLatte.isSelected()==true){
            Pesanan [9][0] = "Avocado Latte";
            Pesanan [9][1] = nAvocad.getText();
        }
        if (nCaramelLatte.isSelected()==true) {
            Pesanan [10][0] = "Caramel Latte";
            Pesanan [10][1] = nCaramel.getText();
        }
        if (nMatchaLatte.isSelected()==true) {
            Pesanan [11][0] = "Matcha Lattee";
            Pesanan [11][1] = nMatcha.getText();
        }
        if (nVanillashake.isSelected()==true) {
            Pesanan [12][0] = "Vanilla Shake";
            Pesanan [12][1] = nVanilla.getText();
        }
        if (nChocolateshake.isSelected()==true) {
            Pesanan [13][0] = "Chocolate Shake";
            Pesanan [13][1] = nChocolate.getText(); 
        }
        if (nStrawberryshake.isSelected()==true) {
            Pesanan [14][0] = "Strawberry Shake";
            Pesanan [14][1] =nStrawberry.getText();
        }
        if (nCooekiesCream.isSelected()==true) {
            Pesanan [15][0] = "Cookies and Cream";
            Pesanan [15][1] = nCookies.getText();        
        }
        //Bagian Hasil
        StrukPemesanan main = new StrukPemesanan();
        main.Pesanan = this.Pesanan;
        main.setVisible(true);
        String tempPesan1 = "";
        String tempPesan2 = "";
        for (int i=0;i<Pesanan.length;i++){
            if(Pesanan[i][0]!=null && Pesanan[i][1]!=null){
                tempPesan1 += Pesanan[i][0]+" \n";          //untuk mengisi struk minuman
                tempPesan2 += Pesanan[i][1]+" \n";          // untuk mengisi jumlah
            }
        }
        main.setMinum(tempPesan1);
        main.setBanyak(tempPesan2);
        main.namaPesan.setText(main.getMinum());
        main.namaPesan.setEditable(false);
        main.Jumlah.setText(main.getBanyak());
        main.Jumlah.setEditable(false);
        dispose();
    }//GEN-LAST:event_pemesananActionPerformed

    private void nVanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nVanillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nVanillaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public void harga_barangActionPerformed(java.awt.event.ActionEvent evt) {
    }   
    public static void main(String args[]) {
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userlogin().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JCheckBox nAmeric;
    private javax.swing.JTextField nAmericano1;
    private javax.swing.JTextField nAvocad;
    private javax.swing.JCheckBox nAvocadLatte;
    private javax.swing.JCheckBox nBlackC;
    private javax.swing.JTextField nBlackCoffee;
    private javax.swing.JTextField nBlackCoffee13;
    private javax.swing.JTextField nBlackCoffee14;
    private javax.swing.JTextField nBlackCoffee16;
    private javax.swing.JTextField nBlackCoffee2;
    private javax.swing.JTextField nBlackCoffee5;
    private javax.swing.JTextField nCaramel;
    private javax.swing.JCheckBox nCaramelLatte;
    private javax.swing.JTextField nChocolate;
    private javax.swing.JCheckBox nChocolateshake;
    private javax.swing.JTextField nCofeeLatte;
    private javax.swing.JCheckBox nCoffeeLattee;
    private javax.swing.JCheckBox nCooekiesCream;
    private javax.swing.JTextField nCookies;
    private javax.swing.JTextField nDoppio;
    private javax.swing.JCheckBox nDoppioo;
    private javax.swing.JLabel nExpresso;
    private javax.swing.JTextField nGreentea;
    private javax.swing.JTextField nIceTaro;
    private javax.swing.JCheckBox nMachiaato;
    private javax.swing.JTextField nMachiato;
    private javax.swing.JTextField nMatcha;
    private javax.swing.JCheckBox nMatchaLatte;
    private javax.swing.JTextField nOrigin;
    private javax.swing.JCheckBox nOriginThaitea;
    private javax.swing.JTextField nOvaltine;
    private javax.swing.JTextField nStrawberry;
    private javax.swing.JCheckBox nStrawberryshake;
    private javax.swing.JCheckBox nThaiOvaltine;
    private javax.swing.JCheckBox nThaiTaro;
    private javax.swing.JCheckBox nThaiteaGreenTea;
    private javax.swing.JTextField nVanilla;
    private javax.swing.JCheckBox nVanillashake;
    private javax.swing.JButton pemesanan;
    // End of variables declaration//GEN-END:variables
}
